#!/bin/sh

thisfile=$0

target='TARGET'  #target protein name
refer='REFERENCE'  #reference protein name
doout=0 #=1: user defined output name
doncbi=0
pdb='NA';dopdb=0
chain='';dochain=0;led=''
type=3 #=1: normal/single alignemnt file =2: multiple alignment file  =3: fasta sequence file

oldline=$*   #all argvs
echo $0 $oldline
if [ -n "$1" ] ; then
 aaa=`echo $1 | awk '{print substr($1,1,1)}'`  #check if first input is -XXX
 while [ $aaa == "-" ] ; do
  case $1 in
   -target) target=$2; shift 2;;
   -refer) refer=$2; shift 2;;
   -NCBI)doncbi=1;shift;;
   -ncbi)doncbi=1;shift;;
   -pdb)doncbi=1;pdb=$2;dopdb=1;led=$led' '$1' '$2;shift 2;;
   -chain)dochain=1;chain=$2;led=$led' '$1' '$2;shift 2;;
   -out) doout=1;output=$2;shift 2;;
   *) $0; echo "***Fatal error @ $0! Argument $1 is unrecoginized and ignored : $0 $oldline!"; exit;;
  esac
  aaa=`echo "$1" | awk '{print substr($1,1,1)}'`
 done
fi

if [ -n "$1" ] ; then
 input=$1
 if [ -n "$2" ] ; then
   output=$2
   doout=1
 fi
else
cat << ttt
How to build homology model:
0. First choice! : Download homology model from http://swissmodel.expasy.org/repository/
    You can pick different models from different template!
 SWISS MODEL may build better model by searching homologs by itself. See atm4.pdb in ATM/readme
 Seldom happens: SWISS repository gives Xsuccessful (model may not reliable) model than NCBI blastp as in ~/PBRM1 K294.pdb at 24% id
 Amazing! Repository gives model of Exo5 at 20% seq id to AddB, which is impossible to build from NCBI blastp (which aln to kinase). Amazing! See ~/Exo5
  Bad part: Repository randomly predicted none-aln part and generate error model for this region. See TET1/

1. By using online server SWISS-MODEL:
   http://swissmodel.expasy.org/
  WARNing: Remember to add metal atoms back to homology model!!!
  A0: run ./NCBI_blast_PDBs to download all PDBs or homology PDBs from NCBI and analyze available similar PDBs first!!!
  A. Using NCBI alignment (./alignment_ncbi2clustal) or CLUSTALW to align two sequences:
      http://www.genome.jp/tools/clustalw/
     May need to lower gap penelty from 10 to 1 for hard-aligned sequences!!! See DNA2/readme
      Use ./clustal_identity to calculate identity of the results
     Paste two sequeces into window
     NOTE: Don't use long sequence name in fasta file. Otherwise SWISS-MODEL will complain the CLUSTAWL alignment
     WARNing: swissmodel may generate wrong model if there was missing structures as in COUP/readme. May need delete missing parts
  ./alignment_ncbi2clustal can search NCBI with an input sequence file to output CLUSTALW alignment file
  Use NCBI to align several sequences:
   NCBI Blastp website (http://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastp&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome)
 | check 'Align two or more sequences' | Enter Query Sequence (Single Sequence) | Enter Subject Sequences (can be multiple sequence)
    WARNing: NCBI gives Wrong seq aln for M254 in ACTL6A against 4EFH in ACTL6A/. Do not trust it easily. Check strcuture instead!
  A2:  Convert alignment format from NCBI to Clustalw format for homology modeling by ./alignment_ncbi2clustal
    This is because Clustalw website http://www.genome.jp/tools/clustalw/ sometimes cannot get same alignment as NCBI,
     especially when identity is low.  See RLIP76/readme
   ./alignment_ncbi2clustal -target myosin-9 -refer 1I84S Myosin-9_aln.txt
    NOTE: Reference -refer MUST be PDB id w/ Chain. e.g. PDB 1I84 and chain S
  B. Log in SWISS-MODEL account (MUST!)
     Use 'Target-template Alignment Model' in SWISS-MODEL to do Homology modeling 
      by taking CLUSTALW output as input : Click Support Input as 'Target-Template Alignment'
     http://swissmodel.expasy.org/  by reading in CLUSTALW output
  C. Run ./pdb_renumber_residue X.pdb NNN to renumber residues!

2: Clustal Omega: http://www.ebi.ac.uk/Tools/msa/clustalo/
     It can align seqs (only have structural aligment) that NCBI cannot do
     It can generate Phylogenetic Tree of seqs   See JMJD1B/readme
3. Another good site is MultAlin (good images) for alignemnt
     http://multalin.toulouse.inra.fr/multalin/
     Example: ~/ITCH/readme   ~/gata2/readme  JMJD1B/readme
4. WebLogo can do multiple seq alignment and display it in different way (high ide with larger letter): https://weblogo.berkeley.edu/logo.cgi

==========================================
How to predict protein structure from sequence?
  Tools: http://www.expasy.ch/tools/
         http://cmgm.stanford.edu/WWW/www_predict.html
1. I-TASSER is the best server for protein structure prediction according to the recent CASP experiments
   I-TASSER predicts 2O8G-I structure correctly: ~/PP1/readme
   http://zhanglab.ccmb.med.umich.edu/I-TASSER/
   You are requested to cite following articles when you use the I-TASSER server:
   1) Ambrish Roy, Alper Kucukural, Yang Zhang. I-TASSER: a unified platform for automated protein structure and function prediction. Nature Protocols, vol 5, 725-738 (2010).
   2) Yang Zhang. Template-based modeling and free modeling by I-TASSER in CASP7. Proteins, vol 69 (Suppl 8), 108-117 (2007)
   Check GO annotations for I-TASSER output: ./GO_annotation "GO:0008200 GO:0032036 GO:0005246"
   WARNing: input sequence length can affect prediction see ~/DOT1L
How to use I-TASSER to predict dimer structure? See TWIST/   Use: ./ITASSER_dimer
 2014 paper from UCSD Jing Yang built dimer of WR-domain from I-TASSER to show helical WR-domain:
   They use 14xGly linker between two TWIST WR-domain segments 166-202aa. Then use I-TASSER to predict. Later remove the 14-Gly linker

1.5 SAM http://compbio.soe.ucsc.edu/~farmer/cgi-bin/SAM_T08/T08-query.pl
2. Rosetta
3. Homology modeling: SWISS-MODEL http://swissmodel.expasy.org/
4. MODELLER is used for homology or comparative modeling of protein http://salilab.org/modeller/ to download
    run mod9v7 or in Accelrys
From Vav1 fusion protein:
Phyre2: V-H_fus_intensive_Phyre2_20141003.pdb (whole fusion protein)
 Used whole Vav1 based on 3KY9 and RRM1/2/3 domains of HNRNPM.
 However, no prediction of HNRNPM for gap regions where there is no model
I-TASSER: fusion_ITASSER.pdb
 It predicts the every residue of whole protein
 should use short-sequence alignment (~50aa) against PDB, so predicted RRM2/3 of HNRNPM based on known structure.
 However, no whole model of Vav1 based on 3KY9. See fusion_ITASSER.pdb for whole fusion prediction
Raptor : V-H_fus_RaptorX_20141005.pdb
 Not good at all: No usage of known structures
IntFOLD :


================================

Convert alignment format from NCBI to Clustalw format for homology modeling in SWISS-MODEL http://swissmodel.expasy.org/
  This is because Clustalw website http://www.genome.jp/tools/clustalw/ sometimes cannot get same alignment as NCBI,
   while NCBI's alignment looks much better, 
     especially when identity is low. See RLIP76/readme
 NOTE: this file can take fasta sequence file as input to generate SWISS-MODEL file 

Format of NCBI Alignement file:
    ...
Query  177  EVPQIDVPNLKPIFGIPLADAVERTMMYDGIRLPAVFRECIDYVEKYGMKCEGIYRVSGI  236
             VP    P+LK I  +   D       ++  R P V   CI  +E  G+K EG+YRVSG
Sbjct  257  HVPNDCQPDLKRIKKVYCCDLTTLVKAHNTQR-PMVVDICIREIEARGLKSEGLYRVSGF  315

 Format of Clustalw_Alignment file:
CLUSTAL 2.1 multiple sequence alignment


RLIP76          HKEEKHKEKKSKDLTAADVVKQWKEKKKKKKPIQEPEVPQIDVPNLKPIFGIPLADAVER
1XA6            --------------------VRCSDCGLNVHKQCSKHVPNDCQPDLKRIKKVYCCDLTTL
                                     : .:   : :   . .**:   *:** *  :  .* .

SWISS-MODEL only need aligned lines (2nd row must be PDB id w/ chain):
RLIP76          HKEEKHKEKKSKDLTAADVVKQWKEKKKKKKPIQEPEVPQIDVPNLKPIFGIPLADAVER
1XA6            --------------------VRCSDCGLNVHKQCSKHVPNDCQPDLKRIKKVYCCDLTTL


 Usage: [Options] $0 Input [Output_Clustalw_Alignment]
  Input may has 3 types (auto-detect):
  1. Normal/Single NCBI_Alignment file as shown above
  2. multiple PDBs NCBI_Alignments file. Use -ncbi
  3. Sequence fasta file
 Options:
  X-ncbi | -NCBI : Input is multiple PDBs from NCBI Blast saved as NCBI_Blast_Output.txt : See ubiquitin/NCBI_blast.txt
    Blast on seqeunce agaist PDB at NCBI | Sequences producing significant alignments: | Download | Text
    http://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastp&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome
   -pdb PDBName : PDB name in 4-letter. Either upper/lower cases.
   -chain ChainName : chain name. Default: any chain
  -target TARGET_NAME : name to replace target protein "Query"
  -refer REFERENCE_NAME : name to replace reference protein "Subjct". MUST be PDB id w/ chains
  -out Output : Output Clustalw_Alignment name  [default]: Input.aln

 Example: $0 -target RLIP76 -refer 1XA6A NCBI.txt
            #Single PDB (1XA6, chain A) alignment from NCBI blast 
          $0 -ncbi -pdb 1UL1 -target RLIP76 -refer 1UL1 NCBI_blast.txt
            #Multiple PDBs from NCBI blast file: To extract alignment to PDB 1UL1  
          $0 -target myosin-9 -refer 1I84S Myosin-9_aln.txt
            #NOTE: MUST for Reference is PDB 1I84 Chain S
          $0 -pdb 1UL1 -chain B  A.fasta.txt 

NOTE: NCBI blastp cannot work on PDBs 4c8d and 2oq6 need structural alignment (pymol -CE). See JMJD1B/
  In this case, Ref Review paper: nature reviews:genetics 2006. vol7 715
    Clustal Omega and MultAlin cannot do it as well for whole PDB sequences: http://www.ebi.ac.uk/Tools/msa/clustalo/
     It can only do shorter seq with jmjc-domain only in PF02373_full_hs.txt.
     It can generate phylogenetic tree
    MultAlin cannot do it as well: http://multalin.toulouse.inra.fr/multalin
       Good part of MultAlin is it will re-arrange proteins by seq identity. So good to filter identical sequences.
        To totally rule out partially identical seqs, need to check chromosome location of each seq to see if they are same
    NCBI blastp can do PF02373_full_hs.txt aligment, but it is the worst to do multiple aligments
  Or: download the aligned domains from PFAM domain database: But the align could be very bad
    NOTE: SMART seqs are better than Pfam!
WANRing: Pfam database does not include full length of jmjc-domain for JMJC1B/KDM3B in PF02373_full_hs.txt. Wrong!
  Pfam also miss 7 jmjc proteins, while SMART only miss two: JMJD5. SMART database is better!
 Metal binding HLD1562 is not included as Pfam starts from 1594aa. Only include GAPH1689aa.
 Both SAMRT database jmjc_smart_hs.fasta.txt and review paper did it right
 So both Pfam database and Multalin seq aligment are wrong for JMJC1B/KDM3B!


 NOTE: Use ./clustal_identity to calculate identity, gaps etc.
 NOTE: Use ./seq_align_rearrange to re-arrange sequence alignment files from Clustra or Multalin. Also convert align file into fasta file 
 NOTE: -ncbi Input NCBI_Blast_Output.txt can be obtained from ./NCBI_blast_PDBs
 NOTE: Input aligment file can be obtained from ./NCBI_blast_PDBs -pairwise 1UL1A PCNA.fasta_NCBI_blast.txt
 NOTE: T-coffee can base on protein structure (3D-Tcoffee) and has the best alignment for JMJD1B/ jmjc-domains!
 NOTE: ./atom_align (my own code) can do both ligand/fragment alignment and residue align and give best results!
 NOTE: ./ligand_align can do ligand alignment
 NOTE: ./pdb_TMscore use TMscore to determine similarity of two proteins, better than rmsd
 NOTE: structural seq align ./TM_align is more reliable: normal seq conserved P272 does not conserved in structral align. See JMJD1B/
 NOTE: To align sequences from EBI Clustral, run ./clustalo_lwp.pl
 NOTE: To display colored seq aln file: ./gnuplot_LisAln 

 NOTE: NCBI blastp is not a good alignment tools. So it will miss some improtant homologies, See ~/ARI1
   Use other alignment tools such as Clustral, T-coffee to align and build longer model!
   Use SWISS-Model repository (https://swissmodel.expasy.org/repository/uniprot/O14497) to find more homology models!!!
   The other way is to change balstp parameters, especially drop Drop 'Word Size' from default 6 to 3, can find more low id seqs!
   WARNing: alignment from low seq iden may not be reliable and have many choices. See ~/ARI1 R2153


ttt
  exit
fi

ed='/home/holi/database/pipeline_script/'
drd='/home/holi/database/pipeline_script/'; [ -d $drd ] && ed=$drd  #My old computer
drd='/isi-dcnl/flower_data/hongzhi/database/pipeline_script/'; [ -d $drd ] && ed=$drd #holi@p-ngs2
drd='/isi-flower/flower_data/hongzhili/database/pipeline_script/'; [ -d $drd ] && ed=$drd #holi@p-gpu1
drd='/net/isi-dcnl/ifs/user_data/hongzhi/database/pipeline_script/'; [ -d $drd ] && ed=$drd ##holi@hpc-access1.coh.org
drd='/flower_data/hongzhili/database/pipeline_script/'; [ -d $drd ] && ed=$drd #holi@scalemp1
drd='/home/holi/database/pipeline_script/'; [ -d $drd ] && ed=$drd  #My newest computer
thisfolder=`pwd`; thisfolder=$thisfolder'/'
if [ $thisfolder != $ed ] ; then
 cp -f $ed/back $ed/get $ed/NCBI_blast_getAlignment $ed/NCBI_blast_PDBs $ed/pdb_renumber_residue $ed/pdb_change_chainName .
fi
temp=$0'_'$$'.tmp';  temp2=$temp'2' ; temp3=$temp'3' ; temp4=$temp'4'; temp5=$temp'5'; temp6=$temp'6'

[ $doout -eq 0 ] && output=$input.aln

ist=`grep 'Query' $input | wc -l | awk '{print $1}'`
if [ $ist -eq 0 ] ; then
 echo "Input $input is a fasta seqeuence file"
 type=3
else
 istt=`grep '>pdb' $input | awk '{hh=substr($_,1,5);if(hh==">pdb|"){print $_}}' | wc -l | awk '{print $1}'`
 if [ $istt -gt 1 ] ; then
  echo "Input $input is a multiple alignment file"
  type=2
 else
  echo "Input $input is a single alignment file"
  type=1
 fi
fi
shiftnum=`awk '{if($1=="Query"){print $2;exit}}' $input`
[ "$shiftnum" == "" ] && shiftnum=123

if [ $type -eq 3 ] ; then
 ./NCBI_blast_PDBs -pairwise $pdb$chain -alignout $temp $input 
 input=$temp
fi

if [ $type -eq 2 ] ; then
 ./NCBI_blast_getAlignment $led -out $temp $input
 input=$temp
fi

cat $input | awk 'BEGIN{pn="'$target'";rn="'$refer'";pro="'$thisfile'";s=0;
print "CLUSTAL 2.1 multiple sequence alignment from conversion of NCBI site by ",pro; print " ";print " ";
}
{
 if(s==2){
   s=0;printf("%-16s%s\n",rn,$3);
   printf("    %s\n",seq);
   print " ";
 }
 if(s==1){s=2;seq=substr($_,f1);gsub(/+/,".",seq);gsub(/[a-z]/,"*",seq)}
 if($1=="Query"){
  s=1;
  printf("%-16s%s\n",pn,$3)
  first=sprintf(" %s",substr($3,1,1))
  fl=match($_,first)+1  #find start poisition of sequence #3
  #print "First=",fl,first 
 }
}' > $output

cat $output
echo "***************************************************************"
echo "Convert NCBI alignemnt $input to CLUSTAL alignment in $output"
echo "  1. For homology model, copy/paste above to: http://swissmodel.expasy.org/   Select: Target-template Alignment Model"
echo "     Download model.pdb, then: mv ~/Downloads/*pdb ${target}.pdb"         
echo "  2. Remember to renumber website model: ./pdb_renumber_residue ${target}.pdb $shiftnum"
echo "  3. May need to change model chain name: ./pdb_change_chainName ${target}.pdb NewChainName [OutputPDB]"
echo " "

cat << eee
  WARNing: If SwissModel generates shifted wrong model, it could be missing structures in middle
    May need to delete the partial alignment to get correct model as in COUP/readme
  NOTE: NCBI blastp cannot work on PDBs need structural alignment (pymol -CE). See JMJD1B/
  In this case,
    Clustal Omega can do it and also phylogenetic tree: http://www.ebi.ac.uk/Tools/msa/clustalo/
     Or use my script ./clustal_seq_align
    MultAlin can do it: http://multalin.toulouse.inra.fr/multalin
       Good part of MultAlin is it will re-arrange proteins by seq identity. So good to filter identical sequences.
        To totally rule out partially identical seqs, need to check chromosome location of each seq to see if they are same
   Or: download the aligned domains from PFAM domain database

  If need build homology model from seq directly: Need login first cohemail hy
   Paste seq | Search For Template | Pick one template to build model

 Predict structure: use I-TASSER 
 To predict dimer structure from I-TASSER: add fake Glys from two protein by ./ITASSER_dimer, then use I-TASSER (see TWIST/)

 NOTE: NCBI blastp is not a good alignment tools. So it will miss some improtant homologies or alignment, See ~/ARI1
 WARNing: NCBI gives Wrong seq aln for M254 in ACTL6A against 4EFH in ACTL6A/. Do not trust it easily. Check strcuture instead!
   Use other alignment tools such as Clustral, T-coffee to align and build longer model!
   Use SWISS-Model repository (https://swissmodel.expasy.org/repository/uniprot/O14497) to find more homology models!!!
   The other way is to change balstp parameters, especially drop Drop 'Word Size' from default 6 to 3, can find more low id seqs!
   WARNing: alignment from low seq iden may not be reliable and have many choices. See ~/ARI1 R2153
 NOTE: You can use SWISS directly generate homology model for any PDB by seraching for template and build model on selected template! 

eee

rm -rf $temp
exit
