#!/bin/sh
#Save all scripts to ~/database/pipeline_script
# Script template is ./template 


thisfile=$0
dohet=1 #=0: will NOT count HETATM
dowat=1 #=0: Exclude water HOH or TIP
docenter=2 #=1: only center distance

chain1='+' # ChainName is 1-char, + for whole protein, - for empty chain
chain2='+' # ChainName is 1-char, + for whole protein, - for empty chain
resname1='N/A'
resname2='N/A'
resid1=0
resid2=0
atom1='N/A'
atom2='N/A'

cutoff=3

oldline=$*   #all argvs
#echo $0 $oldline
if [ -n "$1" ] ; then
 aaa=`echo $1 | awk '{print substr($1,1,1)}'`  #check if first input is -XXX
 while [ $aaa == "-" ] ; do
  case $1 in
   -cutoff) cutoff=$2;shift 2;;
   -chain1) chain1=$2;shift 2;;
   -chain2) chain2=$2;shift 2;;
   -resn1) resname1=$2;shift 2;;
   -resn2) resname2=$2;shift 2;;
   -resid1) resid1=$2;shift 2;;
   -resid2) resid2=$2;shift 2;;
   -atom1) atom1=$2;shift 2;;
   -atom2) atom2=$2;shift 2;;
   -nohet) dohet=0;shift;;
   -het) dohet=1;shift;;
   -water) dowat=1;shift;;
   -nowater) dowat=0;shift;;
   -center) docenter=1;shift;;
   -min) docenter=0;shift;;
   *) $0; echo "***Fatal error @ $0! Argument $1 is unrecoginized and ignored : $0 $oldline!"; exit;;
  esac
  aaa=`echo "$1" | awk '{print substr($1,1,1)}'`
 done
fi

if [ -n "$1" ] ; then
 input=$1
else
cat << ttt

 Return Chains inside PDB

 Usage: [Options] $0 InputPDB 
  Screen-dump: Chain names. 
    e.g: ABC  for chain A,B,C
         - for empty chain

 Options:

 Example: $0  RR.pdb

ttt
  exit
fi

infile=`echo $input | awk '{l=length($1)-3;if(substr($1,l,4)==".pdb"){print substr($1,1,l-1)}else{print $1}}'`
input=$infile'.pdb'
temp=$0'_'$$'.tmp';  temp2=$temp'2' ; temp3=$temp'3' ; temp4=$temp'4'


cat $input | awk 'BEGIN{
}
{
 if($1=="ATOM"){
 did=0
 resname=substr($_,18,3)
 atom=$3
 ch=substr($_,22,1)
 if(ch==" "){ch="-"}
 if(!a[ch]){a[ch]=ch}
 }
}END{for(x in a){printf("%s",x)};printf("\n")}' 

rm -f $temp $temp2 $temp3 $temp4 ; exit
